version: "3.7"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#

services:
  default_database:
    restart: unless-stopped
    image: postgis/postgis:15-3.3
    volumes:
      - default_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"

  test_database:
    restart: unless-stopped
    image: postgis/postgis:15-3.3
    volumes:
      - test_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TEST_DATABASE_DB}
      - POSTGRES_USER=${TEST_DATABASE_USER}
      - POSTGRES_PASSWORD=${TEST_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${TEST_DATABASE_PORT}:5432"

volumes:
  test_database_data:
  default_database_data:
